# Generated by Django 5.2.1 on 2026-01-07 18:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('restaurants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WasteCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category_type', models.CharField(choices=[('spoilage', 'Spoilage/Expired'), ('preparation', 'Preparation Waste'), ('overproduction', 'Overproduction'), ('customer_return', 'Customer Return'), ('damaged', 'Damaged Goods'), ('theft', 'Theft/Suspected Theft'), ('portion_control', 'Portion Control Issue'), ('other', 'Other')], default='other', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('color_code', models.CharField(default='#666666', max_length=7)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('requires_approval', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waste_categories', to='restaurants.restaurant')),
            ],
            options={
                'verbose_name_plural': 'Waste Categories',
                'ordering': ['sort_order', 'name'],
                'unique_together': {('restaurant', 'name')},
            },
        ),
        migrations.CreateModel(
            name='WasteReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('controllability', models.CharField(choices=[('controllable', 'Controllable'), ('uncontrollable', 'Uncontrollable'), ('partially_controllable', 'Partially Controllable')], default='controllable', max_length=30)),
                ('requires_explanation', models.BooleanField(default=False)),
                ('requires_photo', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('alert_threshold_daily', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('alert_threshold_weekly', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reasons', to='waste_tracker.wastecategory')),
            ],
            options={
                'ordering': ['category', 'name'],
                'unique_together': {('category', 'name')},
            },
        ),
        migrations.CreateModel(
            name='WasteRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waste_source', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('pending', '⏳ Pending Review'), ('approved', '✅ Approved'), ('rejected', '❌ Rejected'), ('investigating', '🔍 Under Investigation')], default='pending', max_length=30)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('station', models.CharField(blank=True, max_length=100)),
                ('shift', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('corrective_action', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='waste_photos/%Y/%m/%d/')),
                ('batch_number', models.CharField(blank=True, max_length=100, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('is_recurring_issue', models.BooleanField(default=False)),
                ('recurrence_id', models.UUIDField(blank=True, null=True)),
                ('requires_followup', models.BooleanField(default=False)),
                ('followup_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waste_records', to='restaurants.branch')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waste_records_recorded', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waste_records_reviewed', to=settings.AUTH_USER_MODEL)),
                ('stock_transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='waste_detail', to='inventory.stocktransaction')),
                ('waste_reason', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='waste_tracker.wastereason')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WasteAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('threshold_exceeded', 'Threshold Exceeded'), ('recurring_issue', 'Recurring Issue'), ('approval_needed', 'Approval Needed'), ('target_at_risk', 'Target at Risk')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurants.branch')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('waste_reason', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='waste_tracker.wastereason')),
                ('waste_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='waste_tracker.wasterecord')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WasteTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('target_type', models.CharField(choices=[('cost', 'Cost Target ($)'), ('percentage', 'Percentage of Sales (%)'), ('quantity', 'Quantity Target')], max_length=50)),
                ('target_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('period', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='monthly', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('current_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurants.branch')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waste_targets', to='restaurants.restaurant')),
                ('waste_categories', models.ManyToManyField(blank=True, to='waste_tracker.wastecategory')),
            ],
            options={
                'ordering': ['-start_date', 'name'],
            },
        ),
        migrations.AddIndex(
            model_name='wasterecord',
            index=models.Index(fields=['status', 'created_at'], name='waste_track_status_5354d6_idx'),
        ),
        migrations.AddIndex(
            model_name='wasterecord',
            index=models.Index(fields=['branch', 'created_at'], name='waste_track_branch__c61e43_idx'),
        ),
        migrations.AddIndex(
            model_name='wasterecord',
            index=models.Index(fields=['waste_reason', 'created_at'], name='waste_track_waste_r_02656a_idx'),
        ),
    ]
