# Generated by Django 5.2.1 on 2026-01-07 19:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wasterecord',
            name='corrected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wasterecord',
            name='recorded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wasterecord',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wasterecord',
            name='waste_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='wasterecord',
            name='waste_occurred_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
