# Generated by Django 5.2.1 on 2026-01-19 12:48

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_menuitem_cost_price_menuitem_last_sold_and_more'),
        ('profit_intelligence', '0001_initial'),
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuitemperformance',
            options={'ordering': ['-date', '-revenue']},
        ),
        migrations.AlterModelOptions(
            name='profitaggregation',
            options={'ordering': ['-date']},
        ),
        migrations.RemoveIndex(
            model_name='menuitemperformance',
            name='profit_inte_date_b3397d_idx',
        ),
        migrations.RemoveIndex(
            model_name='menuitemperformance',
            name='profit_inte_revenue_7b049d_idx',
        ),
        migrations.RemoveIndex(
            model_name='menuitemperformance',
            name='profit_inte_profit__a3c00e_idx',
        ),
        migrations.RemoveIndex(
            model_name='profitaggregation',
            name='profit_inte_restaur_e009a1_idx',
        ),
        migrations.RemoveIndex(
            model_name='profitaggregation',
            name='profit_inte_profit__b1ca67_idx',
        ),
        migrations.RemoveIndex(
            model_name='profitaggregation',
            name='profit_inte_has_iss_45bbda_idx',
        ),
        migrations.RemoveField(
            model_name='menuitemperformance',
            name='performance_id',
        ),
        migrations.RemoveField(
            model_name='menuitemperformance',
            name='previous_day_quantity',
        ),
        migrations.RemoveField(
            model_name='menuitemperformance',
            name='quantity_change',
        ),
        migrations.RemoveField(
            model_name='menuitemperformance',
            name='trend',
        ),
        migrations.AlterUniqueTogether(
            name='profitaggregation',
            unique_together={('date', 'restaurant', 'branch')},
        ),
        migrations.AddField(
            model_name='menuitemperformance',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='profitaggregation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='menuitemperformance',
            name='calculated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='menuitemperformance',
            name='ingredient_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='menuitemperformance',
            name='labor_cost_share',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='menuitemperformance',
            name='margin_rank',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='menuitemperformance',
            name='menu_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.menuitem'),
        ),
        migrations.AlterField(
            model_name='menuitemperformance',
            name='profit_rank',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='menuitemperformance',
            name='quantity_sold',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='menuitemperformance',
            name='revenue',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='menuitemperformance',
            name='revenue_rank',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='menuitemperformance',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='profitaggregation',
            name='calculated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='profitaggregation',
            name='cost_of_goods',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='profitaggregation',
            name='net_profit',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='profitaggregation',
            name='order_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profitaggregation',
            name='revenue',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='profitaggregation',
            name='waste_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddIndex(
            model_name='menuitemperformance',
            index=models.Index(fields=['date', 'restaurant'], name='profit_inte_date_7a3c19_idx'),
        ),
        migrations.AddIndex(
            model_name='profitaggregation',
            index=models.Index(fields=['restaurant', 'branch', 'date'], name='profit_inte_restaur_ac0e5b_idx'),
        ),
        migrations.RemoveField(
            model_name='profitaggregation',
            name='aggregation_id',
        ),
        migrations.RemoveField(
            model_name='profitaggregation',
            name='customer_count',
        ),
        migrations.RemoveField(
            model_name='profitaggregation',
            name='data_quality_score',
        ),
        migrations.RemoveField(
            model_name='profitaggregation',
            name='gross_profit',
        ),
        migrations.RemoveField(
            model_name='profitaggregation',
            name='has_issues',
        ),
        migrations.RemoveField(
            model_name='profitaggregation',
            name='is_above_target',
        ),
        migrations.RemoveField(
            model_name='profitaggregation',
            name='labor_cost',
        ),
        migrations.RemoveField(
            model_name='profitaggregation',
            name='level',
        ),
        migrations.RemoveField(
            model_name='profitaggregation',
            name='overhead_cost',
        ),
        migrations.RemoveField(
            model_name='profitaggregation',
            name='table_turnover',
        ),
        migrations.RemoveField(
            model_name='profitaggregation',
            name='top_wasted_items',
        ),
        migrations.RemoveField(
            model_name='profitaggregation',
            name='total_cost',
        ),
    ]
