# Generated by Django 5.2.1 on 2026-01-15 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_branch_customuser_restaurant'),
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='managed_branches',
            field=models.ManyToManyField(blank=True, help_text="Branches this manager can access (for 'selected' scope)", related_name='assigned_managers', to='restaurants.branch'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='manager_scope',
            field=models.CharField(blank=True, choices=[('branch', 'Single Branch'), ('selected', 'Selected Branches'), ('restaurant', 'All Restaurant Branches')], default='branch', help_text='Data access scope for managers', max_length=20),
        ),
    ]
