# Generated by Django 5.2.1 on 2026-06-24 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_managed_branches_customuser_manager_scope'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avg_prep_time',
            field=models.IntegerField(default=0, help_text='Average preparation time in minutes (chefs)'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='current_shift',
            field=models.CharField(blank=True, choices=[('morning', 'Morning (6AM-12PM)'), ('afternoon', 'Afternoon (12PM-6PM)'), ('evening', 'Evening (6PM-12AM)'), ('night', 'Night (12AM-6AM)')], help_text='Current shift assignment', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='last_shift_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='last_shift_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='orders_handled',
            field=models.IntegerField(default=0, help_text='Total orders handled (waiters/cashiers)'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='orders_prepared',
            field=models.IntegerField(default=0, help_text='Total orders prepared (chefs)'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='performance_history',
            field=models.JSONField(blank=True, default=list, help_text='Historical performance data for trends'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='performance_score',
            field=models.FloatField(default=0.0, help_text='Overall performance score (0-100)'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Manager rating (0-5)', max_digits=3),
        ),
        migrations.AddField(
            model_name='customuser',
            name='rating_notes',
            field=models.TextField(blank=True, help_text='Manager notes'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='sales_value',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total sales value (waiters/cashiers)', max_digits=12),
        ),
    ]
