# Generated by Django 5.2.1 on 2026-01-06 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='inventory_deducted',
            field=models.BooleanField(default=False, help_text='Whether inventory has been automatically deducted for this order'),
        ),
    ]
