# Generated by Django 5.2.1 on 2026-01-23 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0002_order_inventory_deducted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Waiter Confirmation'), ('confirmed', 'Confirmed by Waiter'), ('preparing', 'Preparing in Kitchen'), ('ready', 'Ready for Serving'), ('served', 'Served to Customer'), ('bill_presented', 'Bill Presented'), ('payment_pending', 'Awaiting Payment'), ('completed', 'Completed (Meal Finished)'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
