# Generated by Django 5.2.1 on 2026-06-24 15:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0004_order_metadata'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='chef',
            field=models.ForeignKey(blank=True, help_text='Chef who prepared this order', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chef_orders', to=settings.AUTH_USER_MODEL),
        ),
    ]
