# Generated by Django 5.2.1 on 2026-01-05 12:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Ingredient cost per serving', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='last_sold',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='profit_margin',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Profit margin percentage (auto-calculated)', max_digits=5),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='sold_count',
            field=models.IntegerField(default=0, help_text='Total units sold'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='total_profit',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total profit generated', max_digits=12),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='total_revenue',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total revenue generated', max_digits=12),
        ),
        migrations.AddIndex(
            model_name='menuitem',
            index=models.Index(fields=['sold_count'], name='menu_menuit_sold_co_3308f9_idx'),
        ),
        migrations.AddIndex(
            model_name='menuitem',
            index=models.Index(fields=['profit_margin'], name='menu_menuit_profit__d1daa0_idx'),
        ),
        migrations.AddIndex(
            model_name='menuitem',
            index=models.Index(fields=['total_revenue'], name='menu_menuit_total_r_b47d5f_idx'),
        ),
    ]
